#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          marytts-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MaryTTS server
# Description:       marytts provides text-to-speech functionalities.
### END INIT INFO

if [ -f /lib/lsb/init-functions ] ; then
    . /lib/lsb/init-functions
fi

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/marytts-server
NAME=marytts
DESC="MaryTTS server"

test -x $DAEMON || exit 0

RUN_AS_USER=marytts
PORT=59125

# Include marytts defaults if available
if [ -f /etc/default/marytts-server ] ; then
    . /etc/default/marytts-server
fi

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
	touch /var/run/$NAME.pid
	chown "$RUN_AS_USER":root /var/run/$NAME.pid
	chmod 644 /var/run/$NAME.pid
	su "$RUN_AS_USER" -s /bin/sh -c "$DAEMON -p /var/run/$NAME.pid -d -- -Dsocket.port=$PORT -Dlog.config=/etc/marytts/log4j.properties" > /dev/null >&2
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	if [ -f /var/run/$NAME.pid ] ; then
	    (kill `cat /var/run/$NAME.pid`) > /dev/null 2>&1 || rm -f /var/run/$NAME.pid
	fi
	echo "$NAME."
	;;
  force-reload)
	# check whether $DAEMON is running. If so, restart
        "$0" stop
	sleep 1
	touch /var/run/$NAME.pid
	chown "$RUN_AS_USER":root /var/run/$NAME.pid
	chmod 644 /var/run/$NAME.pid
	su "$RUN_AS_USER" -s /bin/sh -c "$DAEMON -p /var/run/$NAME.pid -d -k -- -Dsocket.port=$PORT -Dlog.config=/etc/marytts/log4j.properties" > /dev/null >&2
	;;
  restart)
	echo -n "Restarting $DESC: "
        "$0" force-reload
	echo "$NAME."
	;;
  status)
	if [ -s /var/run/$NAME.pid ]; then
            RUNNING=`cat /var/run/$NAME.pid`
            if [ -d /proc/$RUNNING ]; then
		BINARY_NAME=`readlink /proc/$RUNNING/exe`
                if [ `basename $BINARY_NAME` = "java" ]; then
                    echo "$NAME is running."
                    exit 0
                fi
            fi

            # No such PID, or executables don't match
            echo "$NAME is not running, but pidfile existed."
            rm /var/run/$NAME.pid
            exit 1
        else
            rm -f /var/run/$NAME.pid
            echo "$NAME not running."
            exit 1
        fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
